"use client";

// Phase 5 studio — a prompt routes to a Layer 1 hero or a Layer 2 archetype.
// Heroes are built locally and animate; archetypes are generated by the API
// (CadQuery), imported as STEP, and rendered statically. Both flow through the
// same viewport, feature tree, sliders and export path.
import { useEffect, useState } from "react";

import type { HeroId } from "@katacad/shared";

import { FeatureTree } from "@/components/FeatureTree";
import { HeroGallery } from "@/components/HeroGallery";
import { HeroScene } from "@/components/HeroScene";
import { ParameterSliders } from "@/components/ParameterSliders";
import { PromptInput } from "@/components/PromptInput";
import { Viewport } from "@/components/Viewport";
import { generateLayer2 } from "@/lib/api/generate";
import { routePrompt } from "@/lib/api/route";
import { useReplicad } from "@/lib/hooks/useReplicad";
import { downloadBlob } from "@/lib/replicad";
import {
  assembleHero,
  getHero,
  loadArchetype,
  type AnimationFrame,
  type HeroBounds,
  type HeroModel,
  type HeroParams,
} from "@/lib/replicad/heroes";

const FALLBACK_HERO: HeroId = "gearbox";
const STATIC_ANIMATION = (): AnimationFrame => ({});

type StudioRequest =
  | { kind: "hero"; id: HeroId; params: HeroParams }
  | { kind: "archetype"; name: string; params: HeroParams };

/** A shape that can be exported — both heroes and archetypes provide one. */
interface Exportable {
  blobSTEP: () => Blob;
  blobSTL: () => Blob;
}

interface LoadedPart {
  kind: "hero" | "archetype";
  key: string;
  label: string;
  model: HeroModel;
  bounds: HeroBounds;
  exportShape: Exportable;
  params: HeroParams;
  animate: (elapsedSeconds: number, params: HeroParams) => AnimationFrame;
}

export default function StudioClient() {
  const { status } = useReplicad();
  const [request, setRequest] = useState<StudioRequest>({
    kind: "hero",
    id: FALLBACK_HERO,
    params: {},
  });
  const [loaded, setLoaded] = useState<LoadedPart | null>(null);
  const [routing, setRouting] = useState(false);
  const [selectedNode, setSelectedNode] = useState<string | null>(null);

  useEffect(() => {
    if (status !== "ready") return;
    let cancelled = false;

    const buildHero = (id: HeroId, params: HeroParams): void => {
      const definition = getHero(id);
      if (!definition) {
        console.error(`No hero definition registered for "${id}".`);
        return;
      }
      try {
        const merged: HeroParams = { ...definition.defaultParams, ...params };
        const model = definition.build(merged);
        const { compound, bounds } = assembleHero(model);
        if (cancelled) return;
        setLoaded({
          kind: "hero",
          key: id,
          label: definition.label,
          model,
          bounds,
          exportShape: compound,
          params: merged,
          animate: definition.animate,
        });
      } catch (err) {
        console.error(`Failed to build hero "${id}":`, err);
      }
    };

    void (async () => {
      if (request.kind === "hero") {
        buildHero(request.id, request.params);
        return;
      }
      try {
        const response = await generateLayer2({
          archetype: request.name,
          params: request.params,
        });
        const archetype = await loadArchetype(response);
        if (cancelled) return;
        setLoaded({
          kind: "archetype",
          key: request.name,
          label: response.metadata.label,
          model: archetype.model,
          bounds: archetype.bounds,
          exportShape: archetype.shape,
          params: request.params,
          animate: STATIC_ANIMATION,
        });
      } catch (err) {
        console.error("Layer 2 generation failed; loading fallback hero:", err);
        buildHero(FALLBACK_HERO, {});
      }
    })();

    return () => {
      cancelled = true;
    };
  }, [status, request]);

  const load = (next: StudioRequest): void => {
    setSelectedNode(null);
    setRequest(next);
  };

  const handlePrompt = async (prompt: string): Promise<void> => {
    setRouting(true);
    try {
      const result = await routePrompt(prompt);
      if (result.layer === 2 && result.archetype) {
        load({ kind: "archetype", name: result.archetype, params: result.params ?? {} });
      } else if (result.layer === 1 && result.hero && getHero(result.hero as HeroId)) {
        load({ kind: "hero", id: result.hero as HeroId, params: result.params ?? {} });
      } else {
        load({ kind: "hero", id: FALLBACK_HERO, params: {} });
      }
    } catch (err) {
      console.error("Prompt routing failed; loading fallback hero:", err);
      load({ kind: "hero", id: FALLBACK_HERO, params: {} });
    } finally {
      setRouting(false);
    }
  };

  // A slider change keeps the same part but rebuilds it with new parameters.
  const handleSliderChange = (key: string, value: number): void => {
    setRequest((current) =>
      current.kind === "hero"
        ? { kind: "hero", id: current.id, params: { ...current.params, [key]: value } }
        : { kind: "archetype", name: current.name, params: { ...current.params, [key]: value } },
    );
  };

  const handleExport = (kind: "step" | "stl"): void => {
    if (!loaded) return;
    try {
      const blob =
        kind === "step" ? loaded.exportShape.blobSTEP() : loaded.exportShape.blobSTL();
      downloadBlob(blob, `katacad-${loaded.key}.${kind}`);
    } catch (err) {
      console.error(`${kind.toUpperCase()} export failed:`, err);
    }
  };

  const galleryActiveId = loaded?.kind === "hero" ? (loaded.key as HeroId) : null;

  return (
    <main className="flex h-screen flex-col">
      <header className="border-b p-4">
        <h1>KatACAD — Studio</h1>
        <p>Describe a part in plain English, or pick a hero from the gallery below.</p>

        <div className="mt-2">
          <PromptInput onSubmit={handlePrompt} loading={routing} disabled={status !== "ready"} />
        </div>

        <p className="mt-2">
          Kernel status: {status}
          {routing ? " — routing prompt..." : ""}
          {loaded ? ` — showing ${loaded.label}` : ""}
        </p>

        <div className="mt-2 flex gap-2">
          <button type="button" onClick={() => handleExport("step")} disabled={!loaded}>
            Export STEP
          </button>
          <button type="button" onClick={() => handleExport("stl")} disabled={!loaded}>
            Export STL
          </button>
        </div>
      </header>

      <div className="flex flex-1 overflow-hidden">
        <section className="flex-1">
          <Viewport orthographic>
            {loaded ? (
              <HeroScene
                key={`${loaded.kind}:${loaded.key}`}
                model={loaded.model}
                bounds={loaded.bounds}
                animate={(elapsed) => loaded.animate(elapsed, loaded.params)}
                selectedNode={selectedNode}
              />
            ) : null}
          </Viewport>
        </section>

        <aside className="flex w-72 flex-col overflow-hidden border-l">
          <div className="flex-1 overflow-auto">
            {loaded ? (
              <FeatureTree
                root={loaded.model.root}
                selectedNode={selectedNode}
                onSelectNode={setSelectedNode}
              />
            ) : null}
          </div>
          <div className="border-t">
            {loaded ? (
              <ParameterSliders
                sliders={loaded.model.sliders}
                values={loaded.params}
                onChange={handleSliderChange}
                disabled={status !== "ready"}
              />
            ) : null}
          </div>
        </aside>
      </div>

      <HeroGallery
        activeId={galleryActiveId}
        onSelect={(id) => load({ kind: "hero", id, params: {} })}
        disabled={status !== "ready"}
      />
    </main>
  );
}
